/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "ParameterSliderStep.h"


//==============================================================================
/**
*/
class AudioProcessorParameterPluginAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    AudioProcessorParameterPluginAudioProcessorEditor (AudioProcessorParameterPluginAudioProcessor&);
    ~AudioProcessorParameterPluginAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;

private:
    enum SymbolicIndexNames     // Allow use of symbolic names instead
    {                           // of managedParameters indices.
        floatName               // Must have the same ordering as
    };                          // processor's managedParameters!!!

    Label floatLabel_;
    ParameterSliderStep floatSlider_;

    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    AudioProcessorParameterPluginAudioProcessor& processor;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (AudioProcessorParameterPluginAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
